services:
  - name: chat-room-server
    type: web
    env: node
    region: oregon
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
    healthCheckPath: "/server"
